version: '3.7'

services:
  node-exporter:
    hostname: "{{.Node.Hostname}}"
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "128M"
      mode: global

  cadvisor:
    privileged: true
    hostname: "{{.Node.Hostname}}"
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "9080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
      mode: global
